core.entity_view_display.group.open_group.hero:
  expected_config: {  }
  update_actions:
    add:
      content:
        flag_mute_group_notifications:
          weight: 10
          region: content
          settings: { }
          third_party_settings: { }
