core.entity_view_display.profile.profile.preview:
  expected_config:
    content:
      field_profile_self_introduction:
        weight: 4
      flag_follow_user:
        weight: 2
      private_message_link:
        weight: 3
      social_follow_user:
        weight: 5
    hidden:
      field_profile_function: true
  update_actions:
    delete:
      hidden:
        field_profile_function: true
    change:
      content:
        field_profile_self_introduction:
          weight: 5
        flag_follow_user:
          weight: 3
        private_message_link:
          weight: 4
        social_follow_user:
          weight: 6
    add:
      content:
        field_profile_function:
          type: string
          weight: 2
          region: content
          label: visually_hidden
          settings:
            link_to_entity: false
          third_party_settings: {  }
