name: 'Behat'

# Controls when the workflow will run
on:
  # Triggers the workflow on all pull request events
  pull_request: { }

# github.head_ref is only set when the workflow was triggered by a pull_request and it contains the value of the source branch of the PR.
# github.ref_name will than only be used if the workflow was not triggered by a pull_request and it also just contains the branch name.
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  feature_discovery:
    name: "Feature Discovery"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get install jq

      - name: Find feature files
        id: set-matrix
        run: echo "::set-output name=features::$(ls tests/behat/features/capabilities/**/*.feature | jq -R -s -c 'split("\n") | map(select(length > 0))')"

    outputs:
      features: ${{ steps.set-matrix.outputs.features }}

  install_open_social:
    name: "Install Open Social"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        with_optional:
          - ""
          - "--with-optional"
    steps:
      # Set PHP version to 8.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none # disable xdebug, pcov
          tools: cs2pr

      # Checkout Drupal Social.
      - uses: actions/checkout@v3
        with:
          repository: 'goalgorilla/drupal_social'
          ref: '6.1.0'

      # Install the version of Open Social under test.
      - name: Composer require current branch
        run: composer require goalgorilla/open_social:dev-$BRANCH_NAME

      # Install the docker.
      - name: Install Docker
        run: sh scripts/social/ci/install-docker.sh

      - name: Run Docker containers
        run: docker-compose -f docker-compose-ci.yml up -d

      - name: Install Open Social
        run: docker exec -i social_ci_web bash /var/www/scripts/social/install/install_script.sh ${{ matrix.with_optional }} --localsettings

      - name: Dump Database
        run: docker exec -i social_ci_web drush sql:dump --result-file=../installation.sql

      - name: Package up site
        uses: actions/upload-artifact@v3
        with:
          name: test-setup{{ matrix.with_optional }}
          path: ${{ github.workspace }}

  # This workflow contains a single job called "Running tests"
  tests:
    needs: [feature_discovery, install_open_social]

    name: 'Tests'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        with_optional:
          - ""
          - "--with-optional"
        feature: ${{ fromJson(needs.feature_discovery.outputs.features) }}

    steps:
      # Set PHP version to 8.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none # disable xdebug, pcov
          tools: cs2pr

      - uses: actions/download-artifact@v3
        with:
          name: test-setup{{ matrix.with_optional }}

      # Install the docker.
      - name: Install Docker
        run: sh scripts/social/ci/install-docker.sh

      - name: Run Docker containers
        run: docker-compose -f docker-compose-ci.yml up -d

      - name: Load Open Social Database
        run: docker exec -i social_ci_web drush sqlc < installation.sql

      - name: Run Integration test
        run: docker exec -i social_ci_web vendor/bin/behat --config html/profiles/contrib/social/tests/behat/behat.yml --strict --colors ${{ matrix.feature }}

      - name: Upload Behat Test Output
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: behat-output-${{ matrix.feature }}${{ matrix.with_optional }}
          path: html/profiles/contrib/social/tests/behat/logs
