name: Translations

on:
  push:
    branches:
      - main

jobs:
  extract:
    name: Extract
    runs-on: ubuntu-latest
    steps:
      - name: Install Gettext tools
        run: sudo apt-get install gettext
